### ISSUE TITLE
Wrong error by using addToList

### ISSUE THREAD

**Issue by josuavogel** [martin-helmich/typo3-typoscript-parser#58] opened 2021-04-07 14:34 UTC
The following line 

`config.linkVars := addToList(x-inf(1))`

generates the error `Parse error: Unexpected token RVALUE after modify operator.`

**Comment by martin-helmich** [comment] 2021-04-07 15:51
Thanks for the report. This looks like a duplicate of #50.

**Closed by martin-helmich** 2021-04-07 15:51 UTC
Labels: bug
